# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstate.proto\x12\nrdum.state\x1a\x1egoogle/protobuf/duration.proto\"\xa9\x01\n\x05State\x12\r\n\x05tempo\x18\x01 \x01(\r\x12\x0f\n\x07trk_idx\x18\x02 \x01(\x04\x12$\n\x04trks\x18\x03 \x03(\x0b\x32\x16.rdum.state.TrackState\x12\x10\n\x08\x64ivision\x18\x04 \x01(\r\x12\x0b\n\x03len\x18\x05 \x01(\x04\x12*\n\x07latency\x18\x06 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x0f\n\x07playing\x18\x07 \x01(\x08\")\n\nTrackState\x12\r\n\x05slots\x18\x01 \x03(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x9f\x02\n\x0e\x43ommandMessage\x12)\n\x0c\x63ommand_type\x18\x01 \x01(\x0e\x32\x13.rdum.state.Command\x12\x0f\n\x05tempo\x18\x02 \x01(\rH\x00\x12\x12\n\x08\x64ivision\x18\x03 \x01(\rH\x00\x12\x15\n\x0btrack_index\x18\x04 \x01(\x04H\x00\x12\x31\n\x0btoggle_slot\x18\x05 \x01(\x0b\x32\x1a.rdum.state.ToggleSlotArgsH\x00\x12\x18\n\x0enew_track_name\x18\x06 \x01(\tH\x00\x12\x1c\n\x12\x64\x65lete_track_index\x18\x07 \x01(\x04H\x00\x12\x33\n\x0crename_track\x18\x08 \x01(\x0b\x32\x1b.rdum.state.RenameTrackArgsH\x00\x42\x06\n\x04\x61rgs\"$\n\x0eToggleSlotArgs\x12\x12\n\nslot_index\x18\x01 \x01(\x04\"8\n\x0fRenameTrackArgs\x12\x13\n\x0btrack_index\x18\x01 \x01(\x04\x12\x10\n\x08new_name\x18\x02 \x01(\t*\x9f\x02\n\x07\x43ommand\x12\x17\n\x13\x43OMMAND_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x43OMMAND_PLAY_SEQUENCER\x10\x01\x12\x1a\n\x16\x43OMMAND_STOP_SEQUENCER\x10\x02\x12\x15\n\x11\x43OMMAND_SET_TEMPO\x10\x03\x12\x18\n\x14\x43OMMAND_SET_DIVISION\x10\x04\x12\x15\n\x11\x43OMMAND_SET_TRACK\x10\x05\x12\x17\n\x13\x43OMMAND_TOGGLE_SLOT\x10\x06\x12\x17\n\x13\x43OMMAND_CLEAR_TRACK\x10\x07\x12\x15\n\x11\x43OMMAND_ADD_TRACK\x10\x08\x12\x18\n\x14\x43OMMAND_DELETE_TRACK\x10\t\x12\x18\n\x14\x43OMMAND_RENAME_TRACK\x10\nb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=661
  _globals['_COMMAND']._serialized_end=948
  _globals['_STATE']._serialized_start=60
  _globals['_STATE']._serialized_end=229
  _globals['_TRACKSTATE']._serialized_start=231
  _globals['_TRACKSTATE']._serialized_end=272
  _globals['_COMMANDMESSAGE']._serialized_start=275
  _globals['_COMMANDMESSAGE']._serialized_end=562
  _globals['_TOGGLESLOTARGS']._serialized_start=564
  _globals['_TOGGLESLOTARGS']._serialized_end=600
  _globals['_RENAMETRACKARGS']._serialized_start=602
  _globals['_RENAMETRACKARGS']._serialized_end=658
# @@protoc_insertion_point(module_scope)
