# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstate.proto\x12\nrdum.state\x1a\x1egoogle/protobuf/duration.proto\"\xa0\x01\n\x05State\x12\r\n\x05tempo\x18\x01 \x01(\r\x12$\n\x04trks\x18\x03 \x03(\x0b\x32\x16.rdum.state.TrackState\x12\x10\n\x08\x64ivision\x18\x04 \x01(\r\x12\x13\n\x0b\x64\x65\x66\x61ult_len\x18\x05 \x01(\x04\x12*\n\x07latency\x18\x06 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x0f\n\x07playing\x18\x07 \x01(\x08\"C\n\nTrackState\x12\r\n\x05slots\x18\x01 \x03(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03idx\x18\x03 \x01(\x04\x12\x0b\n\x03len\x18\x04 \x01(\x04\"\x9c\x02\n\x0e\x43ommandMessage\x12)\n\x0c\x63ommand_type\x18\x01 \x01(\x0e\x32\x13.rdum.state.Command\x12\x0f\n\x05tempo\x18\x02 \x01(\rH\x00\x12\x17\n\rpattern_index\x18\x03 \x01(\x04H\x00\x12\x12\n\x08\x64ivision\x18\x04 \x01(\rH\x00\x12\x34\n\x0fplay_sound_args\x18\x05 \x01(\x0b\x32\x19.rdum.state.PlaySoundArgsH\x00\x12)\n\tslot_args\x18\x06 \x01(\x0b\x32\x14.rdum.state.SlotArgsH\x00\x12\x38\n\x11track_length_args\x18\x07 \x01(\x0b\x32\x1b.rdum.state.TrackLengthArgsH\x00\x42\x06\n\x04\x61rgs\"E\n\x08SlotArgs\x12\x13\n\x0btrack_index\x18\x01 \x01(\x04\x12\x12\n\nslot_index\x18\x02 \x01(\x04\x12\x10\n\x08velocity\x18\x03 \x01(\r\"<\n\x0fTrackLengthArgs\x12\x13\n\x0btrack_index\x18\x01 \x01(\x04\x12\x14\n\x0ctrack_length\x18\x02 \x01(\x04\"6\n\rPlaySoundArgs\x12\x13\n\x0btrack_index\x18\x01 \x01(\x04\x12\x10\n\x08velocity\x18\x02 \x01(\r*\xae\x02\n\x07\x43ommand\x12\x17\n\x13\x43OMMAND_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x43OMMAND_PLAY_SEQUENCER\x10\x01\x12\x1a\n\x16\x43OMMAND_STOP_SEQUENCER\x10\x02\x12\x15\n\x11\x43OMMAND_SET_TEMPO\x10\x03\x12\x17\n\x13\x43OMMAND_SET_PATTERN\x10\x04\x12\x18\n\x14\x43OMMAND_SET_DIVISION\x10\x05\x12\x16\n\x12\x43OMMAND_PLAY_SOUND\x10\x06\x12\x1d\n\x19\x43OMMAND_SET_SLOT_VELOCITY\x10\x07\x12\x1c\n\x18\x43OMMAND_SET_TRACK_LENGTH\x10\x08\x12\x17\n\x13\x43OMMAND_ADD_PATTERN\x10\t\x12\x1a\n\x16\x43OMMAND_REMOVE_PATTERN\x10\nb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=768
  _globals['_COMMAND']._serialized_end=1070
  _globals['_STATE']._serialized_start=60
  _globals['_STATE']._serialized_end=220
  _globals['_TRACKSTATE']._serialized_start=222
  _globals['_TRACKSTATE']._serialized_end=289
  _globals['_COMMANDMESSAGE']._serialized_start=292
  _globals['_COMMANDMESSAGE']._serialized_end=576
  _globals['_SLOTARGS']._serialized_start=578
  _globals['_SLOTARGS']._serialized_end=647
  _globals['_TRACKLENGTHARGS']._serialized_start=649
  _globals['_TRACKLENGTHARGS']._serialized_end=709
  _globals['_PLAYSOUNDARGS']._serialized_start=711
  _globals['_PLAYSOUNDARGS']._serialized_end=765
# @@protoc_insertion_point(module_scope)
